import { DepartmentType } from '../types/triage.types.js';

export const MEDICAL_DEPARTMENTS: Record<string, DepartmentType> = {
  CARDIAC: 'Cardiac Cath Lab',
  TRAUMA: 'Trauma Level 1',
  STROKE: 'Stroke Center',
  PEDIATRIC: 'Pediatric ICU',
  GENERAL: 'General ER',
};

export const DEFAULT_SEARCH_RADIUS_KM = 50;
export const DEFAULT_AMBULANCE_SPEED_KMH = 50;

export const ERROR_CODES = {
  INVALID_SYMPTOMS: 'INVALID_SYMPTOMS',
  INVALID_COORDINATES: 'INVALID_COORDINATES',
  HOSPITAL_NOT_FOUND: 'HOSPITAL_NOT_FOUND',
  NO_HOSPITALS_FOUND: 'NO_HOSPITALS_FOUND',
  NO_BEDS_AVAILABLE: 'NO_BEDS_AVAILABLE',
  RESERVATION_CONFLICT: 'RESERVATION_CONFLICT',
  INVALID_HOSPITAL_ID: 'INVALID_HOSPITAL_ID',
  ROUTING_SERVICE_ERROR: 'ROUTING_SERVICE_ERROR',
} as const;
